### PR TITLE
Reorganizing Zero to Hero Folder structure

### PR DESCRIPTION
**Pull request by heyjustinai**
Putting Zero to Hero Guide to root for increased visibility

### CODE REVIEW

**Comment by heyjustinai** [comment]
@ashwinb @raghotham Can we get this PR merge for more visibility to zero-to-hero? 
cc: @init27 @wukaixingxp @HamidShojanazeri

**Comment by HamidShojanazeri** [comment]
Thankks @heyjustinai, @raghotham also agreed to this offline.

**Review by ashwinb — APPROVED** [review]

**Comment by ashwinb** [comment]
sorry for late review here --  there are a couple conflicts. if you could rebase, I will get it merged.

**Comment by heyjustinai** [comment]
rebased to main and ready to merge

**Pull request merged**
