### PR TITLE
add databricks provider

### PR DESCRIPTION
**Pull request by prithu-dasgupta**
We want to setup Databricks as a remote inference provider for llama-stack. [Databricks Foundation Model APIs](https://docs.databricks.com/en/machine-learning/foundation-models/index.html) are OpenAI compatible and we suggest using the [OpenAI client](https://docs.databricks.com/en/machine-learning/model-serving/score-foundation-models.html) to query Databricks model serving endpoints.

**How I tested**

`LLAMA_STACK_DIR=. PYTHONPATH=. python -m llama_stack.cli.llama stack build`
(set name as databricks-test and provider as remote::databricks and )

`LLAMA_STACK_DIR=. PYTHONPATH=. python -m llama_stack.cli.llama stack configure databricks-test`
(set databricks workspace url, databricks workspace api token, Llama3.1-70B-Instruct as supported model, other fields as default)

`LLAMA_STACK_DIR=. PYTHONPATH=. python -m llama_stack.cli.llama stack run databricks-test --port 12345`

Query the endpoint
```
> llama-stack % curl -X POST http://localhost:12345/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Llama3.1-70B-Instruct","messages":[{"content":"hello world, write me a 2 sentence poem about the moon", "role": "user"}],"stream":false}'
data: {"completion_message":{"role":"assistant","content":"Silvery light upon my face, \nThe moon's soft glow, a peaceful place.","stop_reason":"end_of_turn","tool_calls":[]},"logprobs":null}

> % curl -X POST http://localhost:12345/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Llama3.1-70B-Instruct","messages":[{"content":"hello world, write me a 2 sentence poem about the moon", "role": "user"}],"stream":true}' 
data: {"event":{"event_type":"start","delta":"","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"Sil","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"very","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" moon","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":",","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" a","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" glowing","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" sphere","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":",\n","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"D","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"ancing","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" in","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" the","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" darkness","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":",","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" calm","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" and","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" clear","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":".","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"complete","delta":"","logprobs":null,"stop_reason":"end_of_turn"}}

(venv) prithu.dasgupta@HPW57GX3RK llama-stack % 
```

### CODE REVIEW

**Comment by dakinggg** [comment]
Hi @raghotham, we've signed the CLA now, so should be ready for review!

**Comment by ashwinb** [comment]
Thanks @dakinggg @prithu-dasgupta 

Could you add a Test Plan to your PR summary with the exact steps you took -- we are especially keen to see if tool calling work correctly or not since this is where we have typically seen issues when using an OpenAI compatible layer.

**Review by ashwinb — CHANGES_REQUESTED** [review]
back to you for the tool-call issue + test plan

**Comment by prithu-dasgupta** [comment]
hi @ashwinb, will definitely update the test plan. is there a standard set of instructions in the repo for testing a new inference adapter locally? I'm trying the following but seeing an error:
```
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack build llama_stack/distribution/templates/local-databricks-build.yaml
Traceback (most recent call last):
  File "/Users/prithu.dasgupta/venv/bin/llama", line 33, in <module>
    sys.exit(load_entry_point('llama-toolchain==0.0.17', 'console_scripts', 'llama')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 94, in _run_stack_build_command
    self._run_stack_build_command_from_build_config(build_config)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 69, in _run_stack_build_command_from_build_config
    build_package(build_config, build_file_path)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/core/package.py", line 55, in build_package
    raise ValueError(
ValueError: Provider `remote::databricks` is not available for API `inference`
```

**Comment by dakinggg** [comment]
Hey @ashwinb @raghotham is there a more updated guide we could follow after recent refactors?

**Review by Kamokam — APPROVED** [review]

**Comment by prithu-dasgupta** [comment]
hi @ashwinb @raghotham I am trying to follow the test plan here https://github.com/meta-llama/llama-stack/pull/136 but am seeing the same issues. would you be able to provide some assistance?

```
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack run databricks --port 12345
usage: llama stack run [-h] [--port PORT] [--disable-ipv6] config
llama stack run: error: File databricks does not exist. Did you run `llama stack build`?
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack build llama_stack/distribution/templates/local-databricks-build.yaml
Traceback (most recent call last):
  File "/Users/prithu.dasgupta/venv/bin/llama", line 33, in <module>
    sys.exit(load_entry_point('llama-toolchain==0.0.17', 'console_scripts', 'llama')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 94, in _run_stack_build_command
    self._run_stack_build_command_from_build_config(build_config)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 69, in _run_stack_build_command_from_build_config
    build_package(build_config, build_file_path)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/core/package.py", line 55, in build_package
    raise ValueError(
ValueError: Provider `remote::databricks` is not available for API `inference`
```

**Comment by prithu-dasgupta** [comment]
hi @ashwinb @raghotham, I am trying to follow the test plan [here](https://github.com/meta-llama/llama-stack/pull/136) which also uses OpenAI client but am seeing the same issues. Would you be able to provide assistance?

```
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack run databricks --port 12345
usage: llama stack run [-h] [--port PORT] [--disable-ipv6] config
llama stack run: error: File databricks does not exist. Did you run `llama stack build`?
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack build llama_stack/distribution/templates/local-databricks-build.yaml
Traceback (most recent call last):
  File "/Users/prithu.dasgupta/venv/bin/llama", line 33, in <module>
    sys.exit(load_entry_point('llama-toolchain==0.0.17', 'console_scripts', 'llama')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 94, in _run_stack_build_command
    self._run_stack_build_command_from_build_config(build_config)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/build.py", line 69, in _run_stack_build_command_from_build_config
    build_package(build_config, build_file_path)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/core/package.py", line 55, in build_package
    raise ValueError(
ValueError: Provider `remote::databricks` is not available for API `inference`
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % llama stack run llama_stack/distribution/templates/local-databricks-build.yaml --port 12345
Traceback (most recent call last):
  File "/Users/prithu.dasgupta/venv/bin/llama", line 33, in <module>
    sys.exit(load_entry_point('llama-toolchain==0.0.17', 'console_scripts', 'llama')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/llama_toolchain/cli/stack/run.py", line 66, in _run_stack_run_cmd
    config = StackRunConfig(**yaml.safe_load(f))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prithu.dasgupta/venv/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for StackRunConfig
built_at
  Field required [type=missing, input_value={'name': 'local-databrick..., 'image_type': 'conda'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
image_name
  Field required [type=missing, input_value={'name': 'local-databrick..., 'image_type': 'conda'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
(venv) prithu.dasgupta@HPW57GX3RK llama-stack % 
```

**Comment by ashwinb** [comment]
Making sure inference provider testing is easy is on our radar as a super hi-pri item. 

For now, you should do the following to completely make sure your current code (as rebased on top of main) is getting picked up:

```
cd llama-stack
LLAMA_STACK_DIR=. PYTHONPATH=. python -m llama_stack.cli.llama stack build <other args>
```

For other commands like `llama stack configure` or `llama stack run` also prefer to use `PYTHONPATH=. python -m llama_stack.cli.llama` instead of `llama` since the `llama` CLI could be pointing to a package your pip-installed and that might have diverged from your code.

**Comment by prithu-dasgupta** [comment]
thanks @ashwinb that worked! updated the databricks provider code and test plan

**Review by ashwinb — APPROVED** [review]
looks good for now. I am accepting and we will merge soon since we have some refactors incoming. we might have more to ask of you with regard to a few more tests once we get enough of our test infra going. 

thanks again!

**Pull request merged**
