### PR TITLE
Make TGI adapter compatible with HF Inference API

### PR DESCRIPTION
**Pull request by Wauplin**
Hi there :wave: This is a follow-up PR after @hanouticelina's work in https://github.com/meta-llama/llama-stack/pull/53 and @hardikjshah's PR https://github.com/meta-llama/llama-stack/pull/84. At the moment the TGI Adapter is suitable for either a local TGI deployment or a server deployed on [Inference Endpoint](https://huggingface.co/docs/inference-endpoints/index).

This PR adds a new type of adapter that works with our serverless [Inference API](https://huggingface.co/docs/api-inference/index) as well. In practice, the adapter is the same, only the `await initiliaze(config)` logic changes to set the correct inference URL to call. 

I also took the opportunity to switch from a sync inference client to `AsyncInferenceClient` since llama-stack supports it (inputs/outputs are the same, it just that it uses `asyncio`/`aiohttp` under the hood).

Finally, I also officially added 3 remote providers: `remote::tgi`, `remote::hf::serverless` and `remote::hf::endpoint`. Each of them is linked to the correct config and then uses the same adapter logic. I added a distribution template for each provider.

Please let me know if I need to change anything :)

Cheers,

Wauplin, from :hugs: 

```
> llama stack build --list-templates

+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| Template Name       | Providers                                | Description                                                                      |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-hf-endpoint   | {                                        | Like local, but use Hugging Face Inference Endpoints for running LLM inference.  |
|                     |   "inference": "remote::hf::endpoint",   | See https://hf.co/docs/api-endpoints.                                            |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-together      | {                                        | Use Together.ai for running LLM inference                                        |
|                     |   "inference": "remote::together",       |                                                                                  |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "remote::together",          |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-fireworks     | {                                        | Use Fireworks.ai for running LLM inference                                       |
|                     |   "inference": "remote::fireworks",      |                                                                                  |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-hf-serverless | {                                        | Like local, but use Hugging Face Inference API (serverless) for running LLM      |
|                     |   "inference": "remote::hf::serverless", | inference.                                                                       |
|                     |   "memory": "meta-reference",            | See https://hf.co/docs/api-inference.                                            |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local               | {                                        | Use code from `llama_stack` itself to serve all llama stack APIs                 |
|                     |   "inference": "meta-reference",         |                                                                                  |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-ollama        | {                                        | Like local, but use ollama for running LLM inference                             |
|                     |   "inference": "remote::ollama",         |                                                                                  |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
| local-tgi           | {                                        | Like local, but use a TGI server for running LLM inference.                      |
|                     |   "inference": "remote::tgi",            |                                                                                  |
|                     |   "memory": "meta-reference",            |                                                                                  |
|                     |   "safety": "meta-reference",            |                                                                                  |
|                     |   "agents": "meta-reference",            |                                                                                  |
|                     |   "telemetry": "meta-reference"          |                                                                                  |
|                     | }                                        |                                                                                  |
+---------------------+------------------------------------------+----------------------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by ashwinb** [comment]
Wonderful, thank you @Wauplin ! 

Could you run code-formatting lints (we need to make it easier and automatic) but here's the basic instructions:
- `pip install pre-commit` 
- `pre-commit install`

**Review by ashwinb — APPROVED** [review]

**Comment by Wauplin** [comment]
Hi @ashwinb thanks for the review! Yes of course, I ran it and committed https://github.com/meta-llama/llama-stack/pull/97/commits/fcb3438031334857ddaa1cc198a45f6de4e53ae4. It detected other lint issues on files I did not change in this PR but I preferred not to commit them (out of scope). Please let me know if that's fine with you :)

**Comment by Wauplin** [comment]
And congrats on the release earlier today! :hugs:

**Comment by ashwinb** [comment]
Great, thanks!

**Pull request merged**
