### PR TITLE
[bugfix] Fix logprobs on meta-reference impl

### PR DESCRIPTION
**Pull request by yanxi0830**
# Context
- logprobs output is broken on meta-reference, and not supported for providers

# Changes
- fix meta-reference to output single value for first token, align w/ llama-models

# Test

image

### CODE REVIEW

**Comment by yanxi0830** [comment]
> Any reason you are killing LogProbConfig? there was a `top_k` param there

I think the `top_k` param is not used. The logprobs that gets passed to `generation` is a bool here: https://github.com/meta-llama/llama-stack/blob/16ba0fa06fd166d1c5a8d43fed9c5734a7c34f29/llama_stack/providers/impls/meta_reference/inference/generation.py#L176-L185

**Comment by raghotham** [comment]
Would it be possible to make top_k work end-to-end, perhaps in a later PR?

**Comment by yanxi0830** [comment]
> Would it be possible to make top_k work end-to-end, perhaps in a later PR?

Filed task here: https://github.com/meta-llama/llama-stack/issues/214

**Review by ashwinb — APPROVED** [review]
great thank you

**Pull request merged**
