### PR TITLE
Add kotlin docs

### PR DESCRIPTION
**Pull request by Riandy**
# What does this PR do?

In short, provide a summary of what this PR does and why. Usually, the relevant context should be present in a linked issue.

Docs update for Kotlin SDK release

## Test Plan

Please describe:
 - tests you ran to verify your changes with result summaries.
 - provide instructions so it can be reproduced.

## Sources

Please link relevant resources if necessary.

## Before submitting

- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Ran pre-commit to handle lint / formatting issues.
- [ ] Read the [contributor guideline](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md),
      Pull Request section?
- [ ] Updated relevant documentation.
- [ ] Wrote necessary unit or integration tests.

### CODE REVIEW

**Comment by Riandy** [comment]
Note: Feel free to review the PR and suggest changes, but don't merge it yet. We will merge this at the same time when we release the Kotlin SDK

**Comment by cmodi-meta** [comment]
@Riandy - Note the readme will need to be updated as well to replace the "TODOs"

**Comment by yanxi0830** [comment]
https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md#building-the-documentation -- you could follow this instructions here to preview the documentation, and attach a screenshot in the test plan.

**Comment by Riandy** [comment]
[
[Llama Stack Client Kotlin API Library — llama-stack documentation v3.pdf](https://github.com/user-attachments/files/18042211/Llama.Stack.Client.Kotlin.API.Library.llama-stack.documentation.v3.pdf)
](url)

How it looks on the docs following https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md#building-the-documentation 
cc: @yanxi0830

**Review by ashwinb — APPROVED** [review]
yeehaw!

**Pull request merged**
