### PR TITLE
Together AI basic integration

### PR DESCRIPTION
**Pull request by Nutlope**
## Why this PR
We want to setup Together.ai as a remote inference provider for llama-stack.

## What is in the PR
- integration with the distribution
- Together AI as a client (with the python `together` SDK)

## How I tested

1. Setup the distribution

```
llama distribution install --spec remote-together --name remote_llama_8b_together
```

2. Start the distribution

```
llama distribution start --name remote_llama_8b_together --port 5555
```

3. Use curl to query the agentic RPC (non-streaming)

```
curl -X POST http://localhost:5555/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Meta-Llama3.1-8B-Instruct","messages":[{"content":"hello world", "role": "user"}],"stream":false}'
```

**Response:**
```
data: {"completion_message":{"role":"assistant","content":"Hello World! It's nice to meet you. Is there something I can help you with, or would you like to chat?","stop_reason":"end_of_turn","tool_calls":[]},"logprobs":null}
```

4. Use curl to query the agentic RPC (streaming)

```
curl -X POST http://localhost:5555/inference/chat_completion -H "Content-Type: application/json" -d '{"model":"Meta-Llama3.1-8B-Instruct","messages":[{"content":"hello world", "role": "user"}],"stream":true}'
```

**Response:**
```
data: {"event":{"event_type":"start","delta":"","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"Hello","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" world","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"!","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" It","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"'s","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" nice","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" to","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" meet","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" you","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"!","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" Is","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" there","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" something","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" I","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" can","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" help","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" you","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" with","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":",","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" or","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" would","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" you","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" like","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" to","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":" chat","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"progress","delta":"?","logprobs":null,"stop_reason":null}}

data: {"event":{"event_type":"complete","delta":"","logprobs":null,"stop_reason":"end_of_turn"}}
```

### CODE REVIEW

**Comment by ashwinb** [comment]
Thank you for this @Nutlope -- do you mind accepting the Facebook CLA? @jeffxtang do you want to test this out once? It looks good to me, so I will merge it as soon as you give the OK.

**Comment by jeffxtang** [comment]
> Thank you for this @Nutlope -- do you mind accepting the Facebook CLA? @jeffxtang do you want to test this out once? It looks good to me, so I will merge it as soon as you give the OK.

Sure @ashwinb I'll test it this morning.

**Comment by Nutlope** [comment]
> Thank you for this @Nutlope -- do you mind accepting the Facebook CLA? @jeffxtang do you want to test this out once? It looks good to me, so I will merge it as soon as you give the OK.

Just accepted it!

**Comment by jeffxtang** [comment]
@ashwinb I just tested the steps and all looks good. 

Thanks @Nutlope for the PR! Will there be a public Together URL for your remote provider soon so we/you can demo this?

**Comment by Nutlope** [comment]
> @ashwinb I just tested the steps and all looks good.
> 
> Thanks @Nutlope for the PR! Will there be a public Together URL for your remote provider soon so we/you can demo this?

I'm not sure what you mean – how do we get this public Together URL? Does it involve deploying this current repo to some server?

**Comment by jeffxtang** [comment]
@Nutlope yes, to your server - so after you run "llama distribution start --name remote_llama_8b_together --port 5555", one can access your service, a Llama stack remote (Together) provider, easily, like in a Colab. But how would the user pass their Together API key which is currently saved locally in your Step 1?

**Comment by Nutlope** [comment]
@jeffxtang Ah I see, I assumed folks would install the `llama` package, start their together distribution, pass in their API key (since the distribution asks you to fill this info), then run it.

Happy to do whatever you think is best! Do you have any additional guidance on how to do this? How have other providers deployed this and shared it as a public URL?

**Comment by ashwinb** [comment]
yeah, we need to build a small piece of infrastructure to make sure user API keys can be forwarded to a remote provider like Together, Fireworks, etc. We will work this in soon; it is necessary. I will land this for now.

**Review by ashwinb — APPROVED** [review]

**Pull request merged**
