### PR TITLE
Distributions updates (slight updates to ollama, add inline-vllm and remote-vllm)

### PR DESCRIPTION
**Pull request by ashwinb**
# What does this PR do?

As the title shows

## Feature/Issue validation/testing/test plan

Will be building and publishing the dockers and then updating this shortly.

### CODE REVIEW

**Review by raghotham — COMMENTED** [review]
can we split out ollama changes into a separate PR or change description to include all changes in this PR?

**Review by terrytangyuan — COMMENTED** [review]
Thanks! There have been some concerns related to performance and hardware support on inline vLLM raised by my colleague @stevegrubb. @ashwinb Any thoughts on that?

**Comment by ashwinb** [comment]
> Thanks! There have been some concerns related to performance and hardware support on inline vLLM raised by my colleague @stevegrubb. @ashwinb Any thoughts on that?

I don't recall performance considerations being raised (although I wouldn't be surprised since nothing is tuned.) IIRC the convo was about not enough configuration options (there are so many) being provided. That is reasonable feedback, but it doesn't preclude us from adding what makes sense and this provides people with an option if they don't want to run another container.

**Review by raghotham — APPROVED** [review]
looks good.

**Review by terrytangyuan — APPROVED** [review]
Thanks. Sounds good.

**Pull request merged**
