### PR TITLE
add nvidia nim inference provider to docs

### PR DESCRIPTION
**Pull request by mattf**
# What does this PR do?

add [NVIDIA NIM](https://build.nvidia.com/nim?filters=nimType%3Anim_type_run_anywhere&q=llama) reference to the docs

## Before submitting

- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Ran pre-commit to handle lint / formatting issues.
- [x] Read the [contributor guideline](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md),
      Pull Request section?
- [x] Updated relevant documentation.
- [ ] Wrote necessary unit or integration tests.

### CODE REVIEW

**Comment by dineshyv** [comment]
can we add a section here too? https://llama-stack.readthedocs.io/en/latest/distributions/index.html

**Review by dineshyv — COMMENTED** [review]
can we add a section here too? https://llama-stack.readthedocs.io/en/latest/distributions/index.html

**Review by dineshyv — CHANGES_REQUESTED** [review]
can we add a section here too? https://llama-stack.readthedocs.io/en/latest/distributions/index.html

**Comment by dineshyv** [comment]
sounds good.

**Review by dineshyv — APPROVED** [review]

**Comment by mattf** [comment]
@dineshyv will you merge this?

**Pull request merged**
